# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 16:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название текста', max_length=100)),
                ('text', ckeditor.fields.RichTextField(help_text='Содержание текста')),
                ('order_id', models.PositiveSmallIntegerField(help_text='Порядковый номер')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=100)),
                ('email', models.EmailField(help_text='почта', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Номер', max_length=128)),
                ('text', models.TextField(help_text='Текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название для фото', max_length=100)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='image', upload_to='media')),
                ('order_id', models.PositiveSmallIntegerField(help_text='Порядковый номер')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название раздела(видно только в админке)', max_length=100)),
                ('order_id', models.PositiveSmallIntegerField(help_text='Порядковый номер')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название для видео', max_length=100)),
                ('link', models.URLField(help_text='Ссылка на видео')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section'),
        ),
    ]
