# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 16:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название текста', max_length=100)),
                ('text', ckeditor.fields.RichTextField(help_text='Содержание текста')),
                ('order_id', models.PositiveSmallIntegerField(help_text='Порядковый номер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='about',
            name='section',
        ),
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.IntegerField(choices=[(0, 'en'), (1, 'ru'), (2, 'ua')], default=0, help_text='язык'),
        ),
    ]
