# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_text_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
