# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='language',
            field=models.IntegerField(choices=[(0, 'en-us'), (1, 'ru'), (2, 'ua')], default=0, help_text='язык'),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.IntegerField(choices=[(0, 'en-us'), (1, 'ru'), (2, 'ua')], default=0, help_text='язык'),
        ),
    ]
