# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20161103_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='background_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=1, help_text='фоновая картинка', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='собственно, фотка', upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(help_text='Ссылка на видео(youtube/etc)'),
        ),
    ]
