# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161103_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=2, help_text='Порядковый номер'),
            preserve_default=False,
        ),
    ]
