# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_video_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='lalalal', help_text='описание для галереи, когда кликаешь на картинку'),
            preserve_default=False,
        ),
    ]
