# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20161103_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='language',
            field=models.IntegerField(choices=[(0, 'en'), (1, 'ru'), (2, 'uk')], default=0, help_text='язык'),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.IntegerField(choices=[(0, 'en'), (1, 'ru'), (2, 'uk')], default=0, help_text='язык'),
        ),
    ]
