# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 16:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20161103_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название. Отражается в ссылке на текст и админке.ТОЛЬКО КИРИЛЛИЦА, без пробелов!!!', max_length=100)),
                ('language', models.IntegerField(choices=[(0, 'en'), (1, 'ru'), (2, 'uk')], help_text='язык')),
                ('text', ckeditor.fields.RichTextField(help_text='Содержание текста.')),
                ('slug', models.SlugField(help_text='Строка для ссылки на текст. Не менять руками!')),
            ],
        ),
    ]
