# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 17:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='text',
        ),
        migrations.AddField(
            model_name='promotion',
            name='text_en',
            field=ckeditor.fields.RichTextField(default='asdasd', help_text='Содержание текста английское.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='text_ru',
            field=ckeditor.fields.RichTextField(default='asd', help_text='Содержание текста русское.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='text_ua',
            field=ckeditor.fields.RichTextField(default='asd', help_text='Содержание текста украинское.'),
            preserve_default=False,
        ),
    ]
