# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20161104_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='language',
        ),
    ]
