# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 02:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_promotion_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название секции(НЕ ТРОГАТЬ)', max_length=100)),
                ('text_en', ckeditor.fields.RichTextField(help_text='Текст секции')),
                ('text_ru', ckeditor.fields.RichTextField(help_text='Текст секции')),
                ('text_ua', ckeditor.fields.RichTextField(help_text='Текст секции')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='section',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
