# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20161105_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название картинки для админки', max_length=100)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='')),
                ('section_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.SectionText')),
            ],
        ),
    ]
