# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_sectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название вилео для админки', max_length=100)),
                ('link', models.URLField(help_text='Ссылка на видео')),
            ],
        ),
    ]
