# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_sectionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionvideo',
            name='section_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.SectionText'),
            preserve_default=False,
        ),
    ]
