# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_sectionvideo_section_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontext',
            name='text_en',
            field=ckeditor.fields.RichTextField(help_text='Текст английский'),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='text_ru',
            field=ckeditor.fields.RichTextField(help_text='Текст русский'),
        ),
        migrations.AlterField(
            model_name='sectiontext',
            name='text_ua',
            field=ckeditor.fields.RichTextField(help_text='Текст украинский'),
        ),
    ]
