# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 03:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20161105_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order_id',
        ),
        migrations.AddField(
            model_name='section',
            name='text_en',
            field=ckeditor.fields.RichTextField(default='asd', help_text='Текст английский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='text_ru',
            field=ckeditor.fields.RichTextField(default='asd', help_text='Текст русский'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='text_ua',
            field=ckeditor.fields.RichTextField(default='asd', help_text='Текст украинский'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Название секции(НЕ ТРОГАТЬ)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionimage',
            name='section_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section'),
        ),
        migrations.AlterField(
            model_name='sectionvideo',
            name='section_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Section'),
        ),
        migrations.DeleteModel(
            name='SectionText',
        ),
    ]
