# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20161105_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Cекция лэндинга', 'verbose_name_plural': 'Секции лэндинга'},
        ),
    ]
