# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20161107_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order_id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order_id']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='order_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, help_text='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='video',
            name='order_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, help_text='Порядковый номер'),
        ),
    ]
