# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20161107_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button_text',
            field=models.CharField(default='button_text', help_text='Текст кнопки', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='heading',
            field=models.CharField(default='heading', help_text='Заголовок', max_length=100),
            preserve_default=False,
        ),
    ]
