# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20161114_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='text_en',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text_ua',
        ),
    ]
