# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20161114_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button_text_en',
            field=models.CharField(help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_ru',
            field=models.CharField(help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_uk',
            field=models.CharField(help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='heading_en',
            field=models.CharField(help_text='Заголовок', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='heading_ru',
            field=models.CharField(help_text='Заголовок', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='heading_uk',
            field=models.CharField(help_text='Заголовок', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст английский', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст английский', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст английский', null=True),
        ),
    ]
