# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20161114_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст английский', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст английский', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст английский', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text_uk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст английский', null=True),
        ),
    ]
