# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20161114_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionvideo',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
