# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_sectionvideo_youtube_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='button_text',
            field=models.CharField(blank=True, help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_text_ru',
            field=models.CharField(blank=True, help_text='Текст кнопки', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_text_uk',
            field=models.CharField(blank=True, help_text='Текст кнопки', max_length=100, null=True),
        ),
    ]
