# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20161115_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show_in_photos',
            field=models.BooleanField(default=False, help_text='Отражать в фото галерее'),
        ),
    ]
